/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package antcolony;

/**
 *
 * @author busra
 */
import com.sun.org.apache.xerces.internal.xs.StringList;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.Shape;
import java.awt.geom.Ellipse2D;
import java.awt.image.ImageObserver;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.text.AttributedCharacterIterator;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import java.awt.*;
import javax.swing.JInternalFrame;


public class NewJFrame extends javax.swing.JFrame {

<<<<<<< HEAD
         ArrayList<Distance> distanceList = new ArrayList<Distance>();
           ArrayList<Town> towns = new ArrayList<Town>();
           ArrayList<Point> showTown = new ArrayList<Point>();
           ArrayList<Ant> ants = new ArrayList<Ant>();
=======
        ArrayList<Distance> distanceList = new ArrayList<Distance>();
        ArrayList<Town> towns = new ArrayList<Town>();
        ArrayList<Point> showTown = new ArrayList<Point>();
        JFrame frame;
>>>>>>> 3800e69c4ca391340ab8c8623205012e494cef11
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setForeground(new java.awt.Color(241, 28, 37));
        jButton1.setText("Dosya Seç");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(166, 202, 205));
        jButton2.setForeground(new java.awt.Color(52, 174, 112));
        jButton2.setText("Başlat");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField1.setText("Feramon Sayısı");
        jTextField1.setAutoscrolls(false);
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField1.setDisabledTextColor(new java.awt.Color(239, 29, 29));

        jTextField2.setForeground(new java.awt.Color(126, 47, 242));
        jTextField2.setText("Karınca Sayısı");

        jTextField3.setText("iterasyon Sayısı");

        jButton3.setText("Sonuc Dosyası kaydet");

        jButton4.setText("Grafik Çizdir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(966, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(175, 175, 175))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(504, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            readFile();
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //algoritmaya başla
        setupAnts();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         new TownShow(showTown).setVisible(true);
        //Grafik ekranını açar.
        //showTown point datasını TownShow JFrame'ine gönderir.
        new TownShow(showTown).setVisible(true);
      
    }//GEN-LAST:event_jButton4ActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
         
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new NewJFrame().setVisible(true);        
            }
        });
    }
    
    public void readFile() throws FileNotFoundException, IOException {

        File file = new File("/home/db/NetBeansProjects/antColony/src/antcolony/berlin52.tsp");     
                //("/home/busra/NetBeansProjects/AntColony/src/antcolony/berlin52.tsp");
        FileReader fileReader = new FileReader(file);
        String line;
        Point nokta;
      
        Town town;
        BufferedReader br = new BufferedReader(fileReader);
        boolean okuma = false;
        try {
            line = br.readLine();

            while (!line.equals("EOF")) {
                if (line.equals("NODE_COORD_SECTION")) {
                    okuma = true;
                }
                line = br.readLine();

                if (okuma && !line.equals("EOF")) {
                    //System.out.println(line);
                    String[] point = line.split(" ");
                    town = new Town();
                    town.setName(point[0]);                   
                    float x = Float.parseFloat(point[1]);
                    float y = Float.parseFloat(point[2]);
                    // System.out.println(String.valueOf(x)+" - " + String.valueOf(y));
                    nokta = new Point((int) x, (int) y);
                    town.setLocation(nokta);
                    towns.add(town);
                   }
            }

        } catch (Exception e) {
            br.close();
        }
        /*for(Town t: towns){
            System.out.println("sehirle: "+ t.getName() +" koordinat " + t.getLocation().x + "   " +t.getLocation().y);
        }*/
        computeDistance(towns);

    }

    public void computeDistance(ArrayList<Town> towns) {
       
        long computedDistance = 0;
        Distance newDistance;
        for(Town source : towns ){
            for(Town destination : towns){
                if(! source.getName().equals(destination.getName())){
                    computedDistance = distance(source.getLocation(), destination.getLocation());
                    newDistance = new Distance();
                    newDistance.setSource(source);
                    newDistance.setDestination(destination);
                    newDistance.setDistance(computedDistance);
                    distanceList.add(newDistance);
                }
            }
        }
        
        
       
       scalingTownToShow();
    }

    public static long distance(Point a, Point b) {
        double dx = a.x - b.x;
        double dy = a.y - b.y;
        return Math.round(Math.sqrt(dx * dx + dy * dy));
    }
    
    // scale each point  to show towns on my  jframe 
    
    public void scalingTownToShow(){
        
        int  xMax, yMax, xMin,yMin,x,y,X,Y,screenMaxX = 1450, screenMinX = 30, screenMaxY = 540 , screenMinY = 35;
        ArrayList<Integer> xList = new ArrayList<Integer>();
        ArrayList<Integer> yList = new ArrayList<Integer>();
        Point p;
      for(Town t : towns){
          
          x = t.getLocation().x;
          y = t.getLocation().y;
          xList.add(x);
          yList.add(y);
      }
      
      xMax = Collections.max(xList);
      yMax = Collections.max(yList);
      xMin = Collections.min(xList);
      yMin = Collections.min(yList);
      
       double xRate=(double) (screenMaxX - screenMinX) / (xMax - xMin);
       double yRate =(double) (screenMaxY - screenMinY) / (yMax - yMin);
       
      for(Town t : towns){
          X = (int) ((t.getLocation().x - xMin) * xRate) + screenMinX;
          Y = (int) ((t.getLocation().y - yMin) * yRate) + screenMinY;
          p = new Point(X,Y);
          
          showTown.add(p);
      }
     // showTowns();
    }

     private void showTowns() {
       ///draw each town on jframe
         
    }
<<<<<<< HEAD
    /******************/
     public void setupAnts(){
         /// randomly allocate each ants
         int townSize = towns.size();
         int antSize  = townSize; // default olarak verildi güncellenecek
         
         for(int i = 0 ; i < antSize ; i++){
            // ants.clear();
             Ant ant  = new Ant();
            // ant.visited.add(i,false);
             ants.add(ant);
             System.out.print("burda");
         }
         
         deneme();
                
     }
     
     
     public void setVisitedTown(Ant ant,Town town){
         ant.tours.add(town);
         ant.visited.add(Integer.parseInt(town.getName()) -1 , true);
     }

     public void deneme(){
         int i = 0; 
         for(Ant ant : ants){
             System.out.println("karınca" +ant.visited.get(i));;
             i++;
         }
     }
     
     
     
     
     
     
=======
     
   

>>>>>>> 3800e69c4ca391340ab8c8623205012e494cef11
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

   
}
